Routes for new Cryptography course
TUM-Dev/TUM.sexy pull request #231
Opened 2023-03-20 11:00 UTC by bellebaum

Updated the `crypto` link -> now held by @schanzen under supervision of the IT Security Chair.
Added a new `crypto-moodle` shortcut for the corresponding Moodle course.

- [x] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles:

2023-03-20 11:03 UTC, joschahenningsen requested changes

2023-03-20 11:03 UTC, joschahenningsen commented on redirect/routes.php
> +            'target'      => 'https://www.moodle.tum.de/course/view.php?id=86223',
This adds a redirect to the moodle page using https://mcrypto.tum.sexy

```suggestion
            'target'      => 'https://www.sec.in.tum.de/i20/teaching/ss-2023/kryptografie',
            'moodle_id' => '86223',
        ],
```

2023-03-20 12:21 UTC, bellebaum commented
Thank you. Good to know this is possible :)

2023-03-24 10:45 UTC, joschahenningsen approved these changes

2023-03-24 10:45 UTC, merged