I2DL Routes Update
TUM-Dev/TUM.sexy pull request #30
Opened 2021-01-06 20:07 UTC by kordianbruck

- [X] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles:

2021-01-06 20:07 UTC, kordianbruck commented
@Husain0007 can you update your fork please?

2021-01-07 14:38 UTC, Husain0007 commented
@kordianbruck I'm unable to understand what you mean.
I have forked the repo from TUM-Devs, should I fork from somewhere else?

2021-01-07 14:43 UTC, joschahenningsen commented
Hi @Husain0007 :wave: thanks for contributing!
Your fork is out of date with this original repo because there are new changes since you forked it. [this](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) is a great resource if you want to understand how to update your fork.

If that doesn't work for you, you can also delete your fork and fork the repository again, make your changes and open a new PR.

2021-01-07 15:00 UTC, Husain0007 commented
@joschahenningsen thanks for sharing that link.
I executed the commands and got a merge conflict in "I2DL Routes Update".
<img width="944" alt="Screenshot 2021-01-07 at 8 26 16 PM" src="https://user-images.githubusercontent.com/26639730/103907128-dfc88680-5126-11eb-97cd-bbce2a7d6d57.png">.
Can you advise how to resolve this?

2021-01-07 15:47 UTC, joschahenningsen commented
I think it would be easier to create a fresh fork, but it's always useful to learn something new :)

Your file should now look something like this: 
```
<<<<<<< HEAD
        'ibmi'             => [
=======
        'i2dl' => [
            'description' => 'Introduction to Deep Learning',
            'target'      => 'https://niessner.github.io/I2DL/',
        ],
        'ibmi' => [
>>>>>>> ac56234... I2DL Routes Update
```

You'll have to update it such that it contains your changes and lines with <<<<<<<, >>>>>>> or ======= are gone. Then you can run 
```
git add redirect/routes.php
git rebase --continue
```
This process may be repeated for multiple commits. After you are done you can push your changes.

2021-01-07 16:03 UTC, Husain0007 commented
@joschahenningsen  thank you so much for clearing that up  :) 
I have made the requisite changes and my branch is now up to date.
If some issues still persist, please let me know.

2021-01-07 16:05 UTC, joschahenningsen requested changes
I'm glad that I could help! Could you please remove `.DS_Store` as it has nothing to do with this website. Also, did you want to add i2dl as well? That change is not present now.

2021-01-07 16:23 UTC, joschahenningsen commented on redirect/routes.php
> +        'ibmi' => [
This still could be formatted, then I'm ready to merge :tada:

2021-01-07 16:47 UTC, joschahenningsen approved these changes

2021-01-07 16:48 UTC, merged

2021-01-07 16:49 UTC, joschahenningsen commented
Awesome, thanks for contributing! :sparkles: If you want to learn more about git, git-tut.tum.sexy contains a very fun tutorial!