Update routes.php
TUM-Dev/TUM.sexy pull request #327
Opened 2024-09-18 17:35 UTC by laxerhd

- [x] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles: 

I made some changes to the links on the frontpage (updated/removed some) and added my own tutorial website.

2024-09-19 08:23 UTC, joschahenningsen requested changes
Amazing! 
Seems like we're using one of the routes you changed in our tests. Can you adapt that test as well?

2024-09-20 06:04 UTC, joschahenningsen submitted a review, later dismissed

2024-09-20 06:04 UTC, joschahenningsen commented on tests/General/MainTest.php
> +        $this->assertStringContainsString('https://www.moodle.tum.de/enrol/index.php?id=100579', $router->getTargetOfSub('mgbs.tum.sexy'));
```suggestion
        $this->assertStringContainsString('https://www.moodle.tum.de/course/index.php?id=100579', $router->getTargetOfSub('mgbs.tum.sexy'));
```

2024-09-22 17:32 UTC, kordianbruck approved these changes

2024-09-22 17:41 UTC, merged

2024-09-22 17:43 UTC, laxerhd commented
Great, thanks!